### PR TITLE
Feature: Don't condense enchanted items + drop returned items on ground if they don't fit in player's inventory

### PR DESCRIPTION
**Pull request by Technoguyfication**
In order to prevent people from accidentally condensing their gear (I've definitely had a few close calls myself), I added a feature that prevents players from condensing any items with enchantments on them. Now that items can be disenchanted with a grindstone, it should be easy for players to remove any enchantments before condensing old tools, etc.. Players can still condense items that only have cursed enchantments on them, since curses cannot be removed with a grindstone.

This option is configurable using `preferences.no_enchanted_condense` It's `true` by default, which disables enchanting condensed items.

In the event that returned items from the condenser cannot fit into the player's inventory (can happen if items are picked up by the player with the condenser inventory open), they will drop on the ground rather than disappearing forever.

### CODE REVIEW

**Comment by Technoguyfication** [comment]
It looks like my auto formatter also touched quite a few other parts of TARDISCondenserListener.java, I can undo those changes if you want.

**Comment by eccentricdevotion** [comment]
> It looks like my auto formatter also touched quite a few other parts of TARDISCondenserListener.java, I can undo those changes if you want.

Yep, I prefer to keep the code style the same, so saves me reformatting it :)

**Comment by Chew** [comment]
> This option is configurable using `preferences.no_enchanted_condense` It's `true` by default

Not sure what the other options are like, but wouldn't this be better as preferences.enchanted_condense (or preferences.condense_enchanted_items?) and have it false by default?

**Comment by Technoguyfication** [comment]
> > This option is configurable using `preferences.no_enchanted_condense` It's `true` by default
> 
> Not sure what the other options are like, but wouldn't this be better as preferences.enchanted_condense (or preferences.condense_enchanted_items?) and have it false by default?

To be honest, I was just following the naming convention of `no_creative_condense` haha

**Comment by Technoguyfication** [comment]
> > It looks like my auto formatter also touched quite a few other parts of TARDISCondenserListener.java, I can undo those changes if you want.
> 
> Yep, I prefer to keep the code style the same, so saves me reformatting it :)

Do you have an eclipse formatter xml file or anything I can use, so my auto formatter settings are the same as yours?

**Comment by eccentricdevotion** [comment]
I don't use eclipse, I'll see what IntelliJ can export, though it's not a big thing so long as it's not a huge PR...

**Comment by eccentricdevotion** [comment]
IntelliJ uses .editorconfig files, you can get an Eclipse plugin here: https://github.com/ncjones/editorconfig-eclipse#readme

https://github.com/eccentricdevotion/TARDIS/blob/v4.0/intellij.editorconfig

**Comment by eccentricdevotion** [comment]
I also use an IntelliJ plugin called SaveActions - https://github.com/dubreuia/intellij-plugin-save-actions

**Comment by Technoguyfication** [comment]
I cleaned up the automatic line breaks, not sure why it's even trimming those down.. I use VSCode, but there's an option to import an Eclipse linter configuration. Honestly might just switch to IntelliJ, I'm not too attached to my Java IDE since I rarely use Java for anything haha

**Comment by eccentricdevotion** [comment]
Cheers!

**Pull request merged**
