### PR TITLE
Add images for new rooms (and table of contents)

### PR DESCRIPTION
**Pull request by Chew**
Room gallery was a bit behind, this adds rooms for 

* Apiary
* Bamboo
* Bird Cage
* Chemistry Lab
* Mob Farm
* Smeltery

And added a table of contents for good enough measure.

### CODE REVIEW

**Comment by Chew** [comment]
Was also thinking about putting a small description below each room title, didn't know where else to put it

**Comment by eccentricdevotion** [comment]
Sounds good to me.
I may update the images at some stage just to give them a consistent look with the others.

**Comment by Chew** [comment]
Sounds good, just wanted to get them up there at least

**Comment by Chew** [comment]
Should also note I was unable to add a Llama stall, probably misconfigured on my end

**Comment by PrincessRTFM** [comment]
Eccentric, if I can weigh in on this, all of my players wished that the gallery images _didn't_ use a custom texture pack because it made it harder to tell what the actual blocks were, which was especially annoying for the ones that had their own custom textures installed.

**Comment by eccentricdevotion** [comment]
I'm quite happy to have vanilla texture screenshots, so long as they're all vanilla :)

**Comment by eccentricdevotion** [comment]
> Should also note I was unable to add a Llama stall pic, probably misconfigured on my end

Oh, and 9dacaf3

**Comment by Chew** [comment]
Could have a JS thing that switches

**Comment by PrincessRTFM** [comment]
You _could_, but it seems needlessly complex. There's need to be a control either on each page to toggle them inline, or on some user settings page to set a cookie which is checked on page load to render the right image, and it would double the number of images needed for all screenshots. Doable, but not what I'd call advisable.

**Comment by Chew** [comment]
We could be super extra and have various photos for each and just have a slideshow of them. I think just a separate page just being like "click to view rooms without the pack"

**Pull request merged**
