### PR TITLE
Add a way to negate specific /tardisprefs sub-commands

### PR DESCRIPTION
**Pull request by Chew**
Also cleans up code a little bit.

This adds a way to _negate_ specific tardis.prefs WITHOUT needing to require them.

### CODE REVIEW

**Comment by eccentricdevotion** [comment]
For completeness, should we not add the permission nodes to _plugin.yml_ as well?

**Comment by Chew** [comment]
We _could_ but doing the whole negating thing was to avoid that

**Comment by eccentricdevotion** [comment]
I'm thinking more from a self-documenting perspective. I've had users in the past wanting to know what permissions are available and looking in _plugin.yml_ to find them.

**Comment by eccentricdevotion** [comment]
<details>
<summary>tardis.prefs nodes</summary>
```
tardis.prefs.*:
    description: Allow players to use /tardisprefs commands.
    children:
      tardis.prefs.auto: true
      tardis.prefs.auto_powerup: true
      tardis.prefs.auto_rescue: true
      tardis.prefs.auto_siege: true
      tardis.prefs.beacon: true
      tardis.prefs.build: true
      tardis.prefs.close_gui: true
      tardis.prefs.difficulty: true
      tardis.prefs.dnd: true
      tardis.prefs.eps: true
      tardis.prefs.eps_message: true
      tardis.prefs.farm: true
      tardis.prefs.flight: true
      tardis.prefs.floor: true
      tardis.prefs.forcefield: true
      tardis.prefs.hads: true
      tardis.prefs.hads_type: true
      tardis.prefs.hum: true
      tardis.prefs.isomorphic: true
      tardis.prefs.key: true
      tardis.prefs.key_menu: true
      tardis.prefs.junk: true
      tardis.prefs.language: true
      tardis.prefs.lanterns: true
      tardis.prefs.lock_containers: true
      tardis.prefs.minecart: true
      tardis.prefs.quotes: true
      tardis.prefs.renderer: true
      tardis.prefs.sfx: true
      tardis.prefs.siege_floor: true
      tardis.prefs.siege_wall: true
      tardis.prefs.sign: true
      tardis.prefs.sonic: true
      tardis.prefs.submarine: true
      tardis.prefs.telepathy: true
      tardis.prefs.travelbar: true
      tardis.prefs.wall: true
      tardis.prefs.wool_lights: true
```
</details>

**Comment by eccentricdevotion** [comment]
Merged thanks :)

**Comment by Chew** [comment]
I can add the info the wiki, just in case!

**Pull request merged**
