### PR TITLE
add new placeholders to the wiki page

### PR DESCRIPTION
**Pull request by Chew**
| `%tardis_ars_status%`                 | Gets the status of the in-progress ARS task                                 |
| `%tardis_in%`                         | Gets whether you're in your TARDIS or not                                |

### CODE REVIEW

**Comment by eccentricdevotion** [comment]
I'm currently adding:
```
%tardis_in_any%
%tardis_in_own%
%tardis_in_whose%
%tardis_in_user_<username>%
```

**Comment by eccentricdevotion** [comment]
11a783c

**Comment by Chew** [comment]
Yep I'll add those too

**Comment by Chew** [comment]
So there's no more `%tardis_in%`? It got split into the 4 new ones?

**Comment by eccentricdevotion** [comment]
> So there's no more `%tardis_in%`? It got split into the 4 new ones?

`%tardis_in%` = `%tardis_in_any%`

**Pull request merged**
