### PR TITLE
Add period character to player name validator

### PR DESCRIPTION
**Pull request by Technoguyfication**
With Geyser's [Floodgate 2.0](https://github.com/GeyserMC/Floodgate/), the default prefix for Bedrock players' usernames is a period. This commit adds support for mentioning those players with commands, as currently you can't `/tardis add` Bedrock players, etc.

### CODE REVIEW

**Comment by eccentricdevotion** [comment]
I've already pulled one of these commits

**Comment by Technoguyfication** [comment]
Oh odd, I'm not sure why github is trying to put it in this PR then. Let me try and fix it on my end

**Comment by eccentricdevotion** [comment]
Your branch needs to pull the changes from mine, or start a new branch based of of mine, before submitting a new PR

**Comment by Technoguyfication** [comment]
Ah okay, let me close this one and create a new one from the correct branch. My apologies!

**Pull request closed without merging**
